### PR TITLE
Update to dual rpc on find divergent block and restore parital

### PR DESCRIPTION
**Pull request by Rishi556**
If not using this, using the `-n` argument to specify a node requires that the trailing `/` be added. With this implemented, it won't matter either way.

### CODE REVIEW

**Comment by bt-cryptomancer** [comment]
This method of API access is not guaranteed to work as it's system dependent (it will not work for the Engine team's primary & backup nodes for example).

Putting this PR into draft status for now, and will close it in a week if there is no further discussion on it.

**Comment by Rishi556** [comment]
I think all nodes supporting this type of calls should be a bare minimum to be classified as a public node. It allows for some handy features, most importantly of which is batching contract and blockchain calls into 1 request.

**Comment by Rishi556** [comment]
Been longer than a week lol. I think supporting this type of call should be a change that the engine team makes.

**Comment by eonwarped** [comment]
This works when you add a slash to the main engine node in the default value, I am okay with this if that gets added.

**Pull request merged**
